### PR TITLE
prevent isoformat error

### PR DESCRIPTION
**Pull request by alanhc**
ret is a sting and don't need to use isoformat again.

### CODE REVIEW

**Comment by danishfastian** [comment]
Please merge this to avoid error discussed below
https://community.blockcerts.org/t/cert-tools-error-attributeerror-str-object-has-no-attribute-isoformat-did-you-mean-format/3222

**Comment by x41lakazam** [comment]
Please merge this !

**Comment by lemoustachiste** [comment]
I will publish the package later today

**Comment by lemoustachiste** [comment]
version 3.0.2 published

**Pull request merged**
