### PR TITLE
Adding displayHtml to @context

### PR DESCRIPTION
**Pull request by sandoche**
- I added displayHtml to @context, without it the signed certificate was invalid
- I am not sure if the "description" schema is the best fit, but at least now it works!

### CODE REVIEW

**Comment by guix77** [comment]
Hi,

If you want i t to be accepted, you should probably provide a PR with the relevant changes only, and not those for Sorbonne.

**Comment by guix77** [comment]
But: thanks for your fix Sandoche. I submitted a clean PR with only the necessary changes here : https://github.com/blockchain-certificates/cert-tools/pull/28

**Comment by sandoche** [comment]
Thanks for removing my personal settings I didn't pay attention.

**Comment by chuycepeda** [comment]
Hey buddies, this fix was amazing... but how will you take it to the additional_per_recipient_fields considering there's an additional "csv_column" element per recipient ??

See... you fixed it for **additional_global_fields** 
`additional_global_fields = {"fields": [{"path": "$.displayHtml","value": "<h1>Some html code</h1>"}, {"path": "$.@context","value": ["https://w3id.org/openbadges/v2", "https://w3id.org/blockcerts/v2", {"displayHtml": { "@id": "schema:description" }}]}]}`

But... in the case of **additional_per_recipient_fields**
`additional_per_recipient_fields = {"fields":[{"path": "$.nombalu","value": "*|NOMBALU|*","csv_column": "nombalu"}, {"path": "$.@context","value": [{"nombalu": { "@id": "schema:nombalu" }}]}]}`

This throws a ....
`
File "/usr/local/lib/python2.7/dist-packages/cert_tools/instantiate_v2_certificate_batch.py", line 68, in instantiate_recipient
    cert = jsonpath_helpers.set_field(cert, field['path'], recipient.additional_fields[field['csv_column']])
KeyError: 'csv_column'
`

I guess I need to add something on the context as well for csv_column but so far no success...

**Pull request closed without merging**
